In [1]:
import torch

In [5]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
y = x + 2
z = y * y + 3
out = z.mean()

In [7]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [8]:
z

tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)

In [9]:
out

tensor(12., grad_fn=<MeanBackward0>)

In [10]:
out.backward()

In [11]:
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [12]:
with torch.no_grad():
    k = x + 1
    print(k)

tensor([[2., 2.],
        [2., 2.]])
