In [1]:
import torch

In [2]:
vector = torch.tensor([1, 2, 3, 4])
vector

tensor([1, 2, 3, 4])

In [3]:
vector.shape

torch.Size([4])

In [4]:
matrix = torch.tensor([[1, 2], [3, 4]])

In [5]:
matrix

tensor([[1, 2],
        [3, 4]])

In [6]:
matrix.shape

torch.Size([2, 2])

In [7]:
tensor = torch.tensor([[[1, 2], [3, 4]], [[1, 2], [3, 4]]])

In [8]:
tensor

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])

In [9]:
tensor.shape

torch.Size([2, 2, 2])