In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 28 * 28, 512)
        self.fc2 = nn.Linear(512, 64)
        self.fc3 = nn.Linear(64, 2)
        
    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = x.view(-1, 16 * 28 * 28)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        return x

In [3]:
net = Net()
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)

In [4]:
input_data = torch.randn(1, 1, 32, 32)
input_data

tensor([[[[ 0.6254, -2.1609,  0.1557,  ...,  0.9138, -1.8761,  1.0646],
          [-0.7210, -0.3534,  1.0290,  ..., -1.8025,  0.9095, -0.0104],
          [ 0.7329, -1.6156, -0.4137,  ..., -1.1720, -0.2129, -0.3474],
          ...,
          [ 1.2227, -0.8306,  0.5604,  ..., -0.9603,  0.6433, -1.1086],
          [-2.4288,  0.8237,  1.0392,  ..., -0.2962, -0.4063, -0.3710],
          [ 2.8093, -0.5135,  1.4065,  ..., -0.8177,  0.6326, -1.7835]]]])

In [6]:
input_data.size()

torch.Size([1, 1, 32, 32])

In [7]:
out = net(input_data)
out

tensor([[ 0.0767, -0.1260]], grad_fn=<AddmmBackward>)

In [8]:
out.size()

torch.Size([1, 2])

In [9]:
target = torch.randn(2)
target = target.view(1, -1)
target

tensor([[-0.2030,  1.2890]])

In [10]:
criterion = nn.L1Loss()
loss = criterion(out, target)
loss

tensor(0.8473, grad_fn=<L1LossBackward>)

In [11]:
net.zero_grad()
loss.backward()

In [13]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.step()

In [14]:
out = net(input_data)
out

tensor([[ 0.0422, -0.1001]], grad_fn=<AddmmBackward>)

In [15]:
out.size()

torch.Size([1, 2])

In [16]:
loss = criterion(out, target)
loss

tensor(0.8171, grad_fn=<L1LossBackward>)