In [15]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [19]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

C:\Users\RCRC\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [23]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [24]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [25]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [26]:
log_reg.decision_function(X_test)[:10]

array([-21.40036141, -32.89622343, -16.4121082 , -79.81951813,
       -48.03525356, -24.18475282, -44.60321901, -24.25056084,
        -1.14143903, -19.00267268])

In [27]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
decision_scores = log_reg.decision_function(X_test)

In [29]:
np.min(decision_scores)

-85.72197563981476

In [30]:
np.max(decision_scores)

19.890494217065623

In [37]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [38]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [39]:
precision_score(y_test, y_predict_2)

0.96

In [40]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [41]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [42]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [44]:
recall_score(y_test, y_predict_3)

0.8888888888888888

In [45]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)