In [1]:
import numpy as np
import matplotlib.pylab as plt
from sklearn import datasets

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
shuffle_indexes = np.random.permutation(len(X))

In [12]:
shuffle_indexes

array([ 74,  34, 121,  13,  25,  31,  76,  54,  78,  37, 108,  55,  60,
       119,  27,  97, 103, 137, 126,  82, 130,  66,  87,  86,  26,  91,
        41, 109,  51,  83,  16, 107, 148, 135, 128,  98,  29,  67, 101,
        52,  69, 125,  10,   3,  53,  48,  58,  47,  18,  61,  88,  77,
        19, 146, 124,   9,  33, 144,   4,  28, 117,  93,  99, 123,  62,
       145, 122, 147,  50, 100, 140,  57,   1,  64, 141,  70,  46,  80,
        44,  36,  32,  17, 102,  38,  35,   2, 136, 149, 105,  24, 133,
       113, 134, 138,  15,   0,  56, 139, 116, 112,  68,  90,  81,  12,
       131,   7,  43,  75,  11, 143,  95, 120,  20,  45, 114,  22, 127,
       142,  89,  40, 118,  59, 132,  85,  72,  63,  71,  96,  21, 104,
        65,  49,   8,   6,   5, 129,  14,  94,  84,  92, 110,  30, 111,
       106,  79, 115,  39,  42,  73,  23])

In [13]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [14]:
test_size

30

In [15]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [16]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [17]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [18]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [19]:
X_test

array([[6.4, 2.9, 4.3, 1.3],
       [4.9, 3.1, 1.5, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3. , 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.5, 2.8, 4.6, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [4.9, 3.6, 1.4, 0.1],
       [6.7, 2.5, 5.8, 1.8],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 2. , 3.5, 1. ],
       [6. , 2.2, 5. , 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [6.3, 2.9, 5.6, 1.8],
       [6.4, 3.1, 5.5, 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [5.8, 2.7, 3.9, 1.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [5. , 3.4, 1.6, 0.4],
       [6.1, 3. , 4.6, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [7.2, 3.6, 6.1, 2.5],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6]])

In [20]:
from playML.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [22]:
from playML.kNN import KNNClassifier

In [23]:
my_knn_clf = KNNClassifier(k=3)

In [24]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [25]:
y_predict = my_knn_clf.predict(X_test)

In [26]:
y_predict

array([0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2, 0,
       1, 1, 2, 2, 0, 1, 1, 1])

In [27]:
y_test

array([0, 2, 1, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 2, 0,
       1, 1, 2, 2, 0, 1, 1, 2])

In [28]:
sum(y_predict == y_test)

28

In [29]:
sum(y_predict == y_test)/len(y_test)

0.9333333333333333

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)